### ISSUE TITLE
Saludo

### ISSUE THREAD

**Issue by jnisperuza** [saul365/iot-workshop#1]
Hola Saul que pena molestarte, te habla Jeison Nisperuza de la Universidad San Mateo de Colombia, es para pedirte el favor si me compartes el repositorio de la practica de que hicimos con tu ayuda, muchas gracias por todo.

**Comment by saul365** [comment]
Hola, sí no te preocupes es este mismo repositorio está dentro de la carpeta llamada [python](/saul365/iot-workshop/tree/master/python)
